/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    roles: Role;
    media: Media;
    locations: Location;
    'business-area-extensions': BusinessAreaExtension;
    'city-site-profiles': CitySiteProfile;
    merchants: Merchant;
    teams: Team;
    brokers: Broker;
    amenities: Amenity;
    buildings: Building;
    'building-merchant-relations': BuildingMerchantRelation;
    'listing-merchant-relations': ListingMerchantRelation;
    listings: Listing;
    leads: Lead;
    customers: Customer;
    'lead-ownership-history': LeadOwnershipHistory;
    'follow-ups': FollowUp;
    pages: Page;
    articles: Article;
    'display-tags': DisplayTag;
    'listing-reviews': ListingReview;
    'listing-reports': ListingReport;
    'information-corrections': InformationCorrection;
    'supply-submissions': SupplySubmission;
    'city-partner-applications': CityPartnerApplication;
    'domain-events': DomainEvent;
    'audit-logs': AuditLog;
    tasks: Task;
    notifications: Notification;
    search: Search;
    forms: Form;
    'form-submissions': FormSubmission;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'business-area-extensions': BusinessAreaExtensionsSelect<false> | BusinessAreaExtensionsSelect<true>;
    'city-site-profiles': CitySiteProfilesSelect<false> | CitySiteProfilesSelect<true>;
    merchants: MerchantsSelect<false> | MerchantsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    brokers: BrokersSelect<false> | BrokersSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    buildings: BuildingsSelect<false> | BuildingsSelect<true>;
    'building-merchant-relations': BuildingMerchantRelationsSelect<false> | BuildingMerchantRelationsSelect<true>;
    'listing-merchant-relations': ListingMerchantRelationsSelect<false> | ListingMerchantRelationsSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'lead-ownership-history': LeadOwnershipHistorySelect<false> | LeadOwnershipHistorySelect<true>;
    'follow-ups': FollowUpsSelect<false> | FollowUpsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'display-tags': DisplayTagsSelect<false> | DisplayTagsSelect<true>;
    'listing-reviews': ListingReviewsSelect<false> | ListingReviewsSelect<true>;
    'listing-reports': ListingReportsSelect<false> | ListingReportsSelect<true>;
    'information-corrections': InformationCorrectionsSelect<false> | InformationCorrectionsSelect<true>;
    'supply-submissions': SupplySubmissionsSelect<false> | SupplySubmissionsSelect<true>;
    'city-partner-applications': CityPartnerApplicationsSelect<false> | CityPartnerApplicationsSelect<true>;
    'domain-events': DomainEventsSelect<false> | DomainEventsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'advisor-service-hours': AdvisorServiceHour;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'advisor-service-hours': AdvisorServiceHoursSelect<false> | AdvisorServiceHoursSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    'core-stats': CoreStatsWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'notify-supply-submission-created': TaskNotifySupplySubmissionCreated;
      'notify-city-partner-application-created': TaskNotifyCityPartnerApplicationCreated;
      'reconcile-city-partner-notification-outbox': TaskReconcileCityPartnerNotificationOutbox;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 用户真实姓名；后台展示用。
   */
  name: string;
  /**
   * 可选登录账号；留空时使用邮箱登录。一旦设置不可修改，且必须唯一。
   */
  loginName?: string | null;
  /**
   * 原始手机号输入。系统自动规范化存入 phone_normalized；查询用 phone_normalized。
   */
  phone?: string | null;
  /**
   * 用于查重和登录；自动从 phone 字段生成，不允许手动编辑。
   */
  phoneNormalized?: string | null;
  /**
   * 停用账号无法登录且旧会话失效；锁定账号在 locked_until 之前无法登录。
   */
  status: 'active' | 'disabled' | 'locked';
  /**
   * 可绑定多个角色；最终权限采用允许并集，账号城市作为最终上限。
   */
  roles?: (number | Role)[] | null;
  /**
   * 账号城市绑定（多城市）。留空表示无城市上限（受角色 dataScope 约束）。
   */
  cityScope?: (number | Location)[] | null;
  /**
   * 账号所属团队（可多个）；销售主管/经纪人按团队归组。
   */
  team?: (number | Team)[] | null;
  /**
   * 停用账号时递增；旧会话 token 与版本不匹配即失效。
   */
  sessionVersion: number;
  /**
   * 连续 5 次失败自动锁定 30 分钟。
   */
  failedLoginCount?: number | null;
  /**
   * 到达此时间后自动解锁。
   */
  lockedUntil?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 内置角色不可删除或改码；自定义角色可编辑菜单/操作/数据/字段四层权限。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * 不可变机器码。内置角色为 ADM/OPS/MGR/BRK/CSR；自定义角色使用大写字母加下划线。
   */
  code: string;
  name: string;
  description?: string | null;
  /**
   * 内置角色不可删除、改码或改变 builtin 标记。
   */
  isBuiltin?: boolean | null;
  status: 'active' | 'inactive';
  /**
   * 数据范围上限；账号城市绑定作为最终上限，不允许角色扩大。
   */
  dataScope: 'global' | 'city' | 'team' | 'self' | 'none';
  /**
   * 菜单权限编码数组（允许并集）；通配符 * 表示全部菜单。
   */
  menuPermissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 操作权限编码数组（允许并集）；通配符 * 表示全部操作。
   */
  operationPermissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 字段权限编码数组（允许并集）。phone:full 看完整手机号；phone:masked 仅看脱敏值；audit:before_after 看审计前后值。
   */
  fieldPermissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * 全局唯一，创建后不可修改（大写字母/数字开头，2–64 位）
   */
  immutableCode: string;
  slug: string;
  /**
   * 固定层级：城市>行政区>商圈；城市>地铁线路>地铁站。创建后不可修改。
   */
  type: 'city' | 'district' | 'business_area' | 'metro_line' | 'metro_station';
  /**
   * 类型决定合法上级；移动不可跨城市。城市无上级。
   */
  parent?: (number | null) | Location;
  /**
   * 由系统按层级自动维护；城市节点本身留空（其城市即自身）。
   */
  city?: (number | null) | Location;
  /**
   * 停用后不出现在新业务候选，但历史引用仍展示。
   */
  status: 'active' | 'disabled';
  /**
   * 仅启用节点可设为可见；停用时强制不可见。
   */
  frontendVisible?: boolean | null;
  /**
   * -90 ~ 90，需与经度成对填写
   */
  centerLatitude?: number | null;
  /**
   * -180 ~ 180，需与纬度成对填写
   */
  centerLongitude?: number | null;
  description?: string | null;
  /**
   * 首页商圈卡的背景图。留空时前台回退为该商圈下首个有封面的楼盘图片。
   */
  coverImage?: (number | null) | Media;
  sortOrder?: number | null;
  /**
   * 乐观锁版本，由系统维护
   */
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  blurDataUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * 团队主管账号；主管须具备 MGR 角色属分配/团队管理门禁（M5）
   */
  manager?: (number | null) | User;
  cityScope?: (number | Location)[] | null;
  status: 'active' | 'disabled';
  /**
   * 乐观锁版本，保存时自动递增
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 本页仅供排障；日常配置请在「商圈管理」中打开对应商圈
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-area-extensions".
 */
export interface BusinessAreaExtension {
  id: number;
  /**
   * 仅可选择已启用商圈；创建后不可更改。基础字段只读同步，不在此页编辑。
   */
  businessArea: number | Location;
  /**
   * GeoJSON Polygon；外环须闭合、坐标合法且不自交。可留空。
   */
  boundary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * -90 ~ 90，需与经度成对填写；可留空。
   */
  extendedCenterLatitude?: number | null;
  /**
   * -180 ~ 180，需与纬度成对填写；可留空。
   */
  extendedCenterLongitude?: number | null;
  /**
   * 单项 1–50 字，去首尾空格，同商圈内自动去重。
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 仅可关联同城、已启用的既有地铁站；不改变站点基础属性。
   */
  metroStations?: (number | Location)[] | null;
  /**
   * 乐观锁版本，由系统维护
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-site-profiles".
 */
export interface CitySiteProfile {
  id: number;
  city: number | Location;
  serviceStatus: 'live' | 'coming-soon';
  switcherVisible: boolean;
  sortOrder: number;
  seoTitle: string;
  seoDescription: string;
  heroEyebrow?: string | null;
  heroHeading?: string | null;
  heroBody?: string | null;
  heroMedia?: (number | null) | Media;
  introHeading?: string | null;
  introBody?: string | null;
  contactHeading?: string | null;
  contactBody?: string | null;
  featuredRegions?: (number | Location)[] | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchants".
 */
export interface Merchant {
  id: number;
  name: string;
  /**
   * 业主 / 中介 / 灵活办公品牌 / 渠道，创建后可改但属固定枚举
   */
  type: 'OWNER' | 'AGENCY' | 'FLEX_OFFICE_BRAND' | 'CHANNEL';
  contactName?: string | null;
  /**
   * 中国大陆手机号，保存时自动规范化（去空格/横线/+86）
   */
  contactPhone?: string | null;
  serviceCities?: (number | Location)[] | null;
  /**
   * 停用前若仍有有效供给关系将被拦截，需先完成影响确认与转派
   */
  status: 'active' | 'disabled';
  qualificationStatus: 'pending' | 'valid' | 'rejected';
  /**
   * 资质状态为「已通过」时必填；到期后不再进入有效供给谓词
   */
  qualificationExpiresAt?: string | null;
  /**
   * 乐观锁版本，保存时自动递增
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brokers".
 */
export interface Broker {
  id: number;
  /**
   * 经纪人展示名，可与账号姓名不同（对外昵称）
   */
  displayName: string;
  /**
   * 一名用户至多绑定一个经纪人档案
   */
  user: number | User;
  team?: (number | null) | Team;
  serviceCities?: (number | Location)[] | null;
  serviceBusinessAreas?: (number | Location)[] | null;
  /**
   * 停用前若仍有未完成线索将被拦截，需先完成转派
   */
  employmentStatus: 'active' | 'disabled';
  /**
   * 乐观锁版本，保存时自动递增
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  name: string;
  category?: ('office-service' | 'space' | 'building' | 'lifestyle') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buildings".
 */
export interface Building {
  id: number;
  name: string;
  slug: string;
  status?: ('draft' | 'published' | 'archived') | null;
  operationalStatus?: ('active' | 'disabled') | null;
  buildingType?: ('office_building' | 'business_park' | 'commercial_complex' | 'serviced_office') | null;
  grade?: ('grade-a' | 'super-grade-a' | 'creative-park' | 'serviced-office') | null;
  verificationStatus?: ('unverified' | 'pending' | 'verified') | null;
  registrationCapability?: ('supported' | 'conditional' | 'not_supported') | null;
  /**
   * 数值越小越靠前
   */
  recommendedOrder?: number | null;
  /**
   * 乐观锁版本号，系统维护
   */
  version?: number | null;
  city?: (number | null) | Location;
  district: number | Location;
  businessDistrict?: (number | null) | Location;
  address?: string | null;
  nearestMetro?: (number | null) | Location;
  latitude?: number | null;
  longitude?: number | null;
  completionDate?: string | null;
  totalFloors?: number | null;
  propertyCompany?: string | null;
  /**
   * 元/㎡/月
   */
  propertyFee?: number | null;
  parkingSpaces?: number | null;
  developerAndScale?: {
    developer?: string | null;
    grossFloorArea?: number | null;
    typicalFloorArea?: number | null;
    standardFloorHeight?: number | null;
    netCeilingHeight?: number | null;
    efficiencyRate?: number | null;
  };
  verticalTransport?: {
    passengerElevators?: number | null;
    freightElevators?: number | null;
    zoningNote?: string | null;
  };
  buildingServices?: {
    airConditioning?: string | null;
    network?: string | null;
    powerSupply?: string | null;
    accessControl?: string | null;
    parkingFee?: string | null;
    serviceHours?: string | null;
  };
  certifications?:
    | {
        name: string;
        certificateNumber?: string | null;
        validFrom?: string | null;
        validTo?: string | null;
        publicVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  verificationInfo?: {
    verifiedAt?: string | null;
    priceVerifiedAt?: string | null;
  };
  coverImage?: (number | null) | Media;
  /**
   * 最多 20 张，可拖拽调整顺序
   */
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  amenities?: (number | Amenity)[] | null;
  mediaItems?:
    | {
        resource: number | Media;
        kind: 'image' | 'floor-plan' | 'video';
        category: 'exterior' | 'lobby' | 'common-area' | 'facilities';
        alt: string;
        capturedAt?: string | null;
        isSchematic?: boolean | null;
        id?: string | null;
      }[]
    | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "building-merchant-relations".
 */
export interface BuildingMerchantRelation {
  id: number;
  building: number | Building;
  merchant: number | Merchant;
  /**
   * 关系生效起始时刻（含）
   */
  effectiveFrom: string;
  /**
   * 关系失效时刻（不含）；留空表示无限期
   */
  effectiveTo?: string | null;
  /**
   * 记录该供给关系建立的业务背景，便于审计与转派追溯
   */
  createdReason?: string | null;
  /**
   * 乐观锁版本，保存时自动递增
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-merchant-relations".
 */
export interface ListingMerchantRelation {
  id: number;
  listing: number | Listing;
  /**
   * 留空则创建时继承所属楼盘当前默认商户的快照;准入门禁由 hook 校验。
   */
  merchant?: (number | null) | Merchant;
  effectiveFrom: string;
  /**
   * 留空表示无限期。
   */
  effectiveTo?: string | null;
  createdReason?: string | null;
  /**
   * 乐观锁版本号,系统维护。
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  title: string;
  /**
   * 留空时根据房源标题自动生成拼音 slug；如手动填写则保留自定义值。用于前台 URL（/listings/xxx）。
   */
  slug: string;
  listingType: 'traditional-office' | 'serviced-office' | 'coworking' | 'full-floor';
  building: number | Building;
  businessType?: ('lease' | 'sale') | null;
  decorationStatus?: ('rough' | 'simple' | 'furnished' | 'fully_fitted') | null;
  registrationStatus?: ('available' | 'conditional' | 'unavailable' | 'confirm') | null;
  /**
   * 价格必须保存金额、币种、周期和单位,禁止仅存展示文本。
   */
  price?: {
    amount?: number | null;
    currency?: 'CNY' | null;
    period?: ('month' | 'day' | 'year') | null;
    unit?: ('sqm' | 'suite' | 'seat') | null;
  };
  /**
   * 价格已迁移至上方结构化价格,此字段仅供过渡期兼容。
   */
  rent?: number | null;
  rentUnit?: ('rmb-sqm-day' | 'rmb-month' | 'rmb-seat-month') | null;
  area?: number | null;
  seats?: number | null;
  floor?: string | null;
  minimumLeaseMonths?: number | null;
  paymentTerms?: string | null;
  availableFrom?: string | null;
  spaceDetails?: {
    efficiencyRate?: number | null;
    seatMin?: number | null;
    seatMax?: number | null;
    orientation?: string | null;
    netCeilingHeight?: number | null;
    isDivisible?: boolean | null;
    furnitureStatus?: ('included' | 'optional' | 'none' | 'confirm') | null;
  };
  costTerms?: {
    depositMonths?: number | null;
    propertyFeeInclusion?: ('included' | 'excluded' | 'confirm') | null;
    propertyFeeAmount?: number | null;
    invoiceStatus?: ('included' | 'extra-tax' | 'unavailable' | 'confirm') | null;
    otherFixedCosts?: string | null;
  };
  isFeatured?: boolean | null;
  /**
   * 由提交/审核流程驱动。
   */
  reviewStatus?: ('not_submitted' | 'pending' | 'approved' | 'rejected') | null;
  /**
   * 由显式发布/下架动作驱动,审核通过不自动上架。
   */
  publicationStatus?: ('draft' | 'published' | 'unpublished' | 'leased') | null;
  /**
   * 商户停用等场景批量置为待复核,不改动审核/发布状态。
   */
  supplyVisibilityHold?: ('normal' | 'pending_recheck') | null;
  /**
   * 乐观锁版本号,系统维护。
   */
  version?: number | null;
  /**
   * 房源供给关系的当前商户;有效期与快照规则见供给关系。
   */
  merchant?: (number | null) | Merchant;
  contactBroker?: (number | null) | Broker;
  verificationInfo?: {
    verifiedAt?: string | null;
    priceVerifiedAt?: string | null;
  };
  coverImage?: (number | null) | Media;
  /**
   * 提交审核要求至少 3 张有效图片。
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  mediaItems?:
    | {
        resource: number | Media;
        kind: 'image' | 'floor-plan' | 'video';
        category: 'workspace' | 'meeting-room' | 'common-area' | 'exterior';
        alt: string;
        capturedAt?: string | null;
        isSchematic?: boolean | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  dataSource?: {
    /**
     * 外部抓取来源标识
     */
    source?: 'huizuxuanzhi' | null;
    /**
     * 源平台原始房源编号
     */
    externalId?: string | null;
    /**
     * 详情页原始 URL
     */
    sourceUrl?: string | null;
    /**
     * 最后一次从源平台同步的时间
     */
    syncedAt?: string | null;
  };
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  company?: string | null;
  status?: ('new' | 'contacted' | 'visited' | 'won' | 'lost') | null;
  source?: ('frontend-form' | 'phone' | 'import' | 'other') | null;
  /**
   * 经纪人停用前须先转派名下未完成线索
   */
  owner?: (number | null) | Broker;
  district?: (number | null) | Location;
  budget?: string | null;
  area?: string | null;
  moveInTime?: string | null;
  interestedListing?: (number | null) | Listing;
  /**
   * 按手机号查重后关联的客户档案（一个客户可关联多条线索）。
   */
  customer?: (number | null) | Customer;
  /**
   * 由阶段状态机服务端流转，无法确定映射时进入人工复核。
   */
  stage?:
    | ('new' | 'pending_assignment' | 'following' | 'qualified' | 'viewing' | 'negotiation' | 'converted' | 'lost')
    | null;
  /**
   * 由分配/认领/转派/进入公海/回收动作单一推导。
   */
  ownershipStatus?: ('unassigned' | 'assigned' | 'public_pool') | null;
  team?: (number | null) | Team;
  city?: ((number | null) | Location) | string;
  areaMin?: number | null;
  areaMax?: number | null;
  budgetMin?: number | null;
  budgetMax?: number | null;
  currency?: ('CNY' | 'USD' | 'HKD') | null;
  billingPeriod?: ('month' | 'day_sqm' | 'year') | null;
  seatCount?: number | null;
  leaseMonths?: number | null;
  moveInDate?: string | null;
  specialRequirements?: string | null;
  /**
   * 查重合并后保留的有效创建时刻，SLA 与分析以此为准。
   */
  effectiveCreatedAt?: string | null;
  effectiveSourceChannel?: string | null;
  /**
   * 原始来源渠道（与 source 并存，后者为旧枚举兼容字段）。
   */
  sourceChannel?: string | null;
  firstValidFollowUpAt?: string | null;
  lastValidFollowUpAt?: string | null;
  /**
   * 由跟进服务写入，供 SLA 与待办排序。
   */
  nextFollowUpAt?: string | null;
  /**
   * 分配/认领成功时快照，参数调整不回写既有线索。
   */
  runtimePolicyVersion?: string | null;
  firstFollowUpSlaSeconds?: number | null;
  publicPoolRecycleSeconds?: number | null;
  claimProtectionSeconds?: number | null;
  dailyClaimLimit?: number | null;
  activeLeadCap?: number | null;
  /**
   * 乐观锁版本号，阶段流转/归属变更时递增（服务端维护）。
   */
  version?: number | null;
  notes?: string | null;
  /**
   * requestId + 标准化手机号 + 目标对象 的哈希。同键重复请求只创建一条 Lead（FP-05 §5）。数据库唯一约束兜底，防止并发请求绕过应用层软幂等检查。
   */
  idempotencyKey?: string | null;
  /**
   * 前台入口页面类型：home / search / listing / building / content。
   */
  sourcePageType?: ('home' | 'search' | 'listing' | 'building' | 'content' | 'entrust') | null;
  /**
   * 前台入口相对路径（白名单化，不含查询参数中的个人信息）。
   */
  sourcePath?: string | null;
  /**
   * 前台入口完整 URL（仅服务端日志记录，不展示给经纪人）。
   */
  sourceUrl?: string | null;
  /**
   * listing / building / none（通用需求）。
   */
  targetType?: ('listing' | 'building' | 'none') | null;
  /**
   * 前台传入的房源 slug；通过 assertEffectiveListing 校验后写入。
   */
  targetListingSlug?: string | null;
  /**
   * 前台传入的楼盘 slug。
   */
  targetBuildingSlug?: string | null;
  /**
   * 仅保存白名单化的详情页入口区块；不保存任意前台文案。
   */
  sourceSection?:
    | ('hero' | 'sticky-card' | 'mobile-bar' | 'supply-lease' | 'supply-sale' | 'supply-coworking' | 'recommendation')
    | null;
  /**
   * 提交时页面当前的供给分组，仅接受 lease / sale / coworking。
   */
  activeSupplyGroup?: ('lease' | 'sale' | 'coworking') | null;
  /**
   * 已白名单化的 group / priceUnit 枚举；不保存自由文本或用户标识。
   */
  currentFilters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 非权威来源快照，仅供跟进参考，不参与公开价格或排序。
   */
  priceSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  priceSnapshotSubmittedAt?: string | null;
  /**
   * 用户必须主动勾选，未勾选不得提交（FP-05 §3.1）。
   */
  consentAccepted?: boolean | null;
  /**
   * 同意时的隐私政策版本号（PRIVACY_POLICY_VERSION）。
   */
  consentPolicyVersion?: string | null;
  /**
   * 白名单化 UTM 参数（utm_source / utm_medium / utm_campaign / utm_content / utm_term），各键值长度 ≤ 100。
   */
  campaign?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 前台生成的请求唯一标识，用于日志关联与幂等键计算。
   */
  requestId?: string | null;
  /**
   * 用户在询盘时选择的偏好看房时段，服务端已复核落在平台服务时间内。始终为“待顾问确认”，不代表已确认预约。
   */
  viewingPreference?: {
    startsAt?: string | null;
    endsAt?: string | null;
    timezone?: string | null;
    status?: 'pending-confirmation' | null;
  };
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * 客户档案：手机号用于查重但不作为业务主键，一个客户可关联多条线索。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  company?: string | null;
  /**
   * 规范化后的手机号，用于 30 天窗口查重（不作为业务主键）。
   */
  phoneNormalized: string;
  /**
   * 脱敏快照（如 138****1111），供列表展示，不含完整号码。
   */
  phoneMaskedSnapshot?: string | null;
  status?: ('active' | 'converted' | 'lost') | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 线索归属流水：分配/认领/转派/进入公海/回收。记录创建后不可修改或删除。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-ownership-history".
 */
export interface LeadOwnershipHistory {
  id: number;
  lead: number | Lead;
  action: 'assign' | 'claim' | 'transfer' | 'to_public_pool' | 'reclaim';
  /**
   * 由归属动作单一推导，不可外部指定。
   */
  ownershipStatus?: ('unassigned' | 'assigned' | 'public_pool') | null;
  fromOwner?: (number | null) | Broker;
  toOwner?: (number | null) | Broker;
  /**
   * 进入公海 / 回收必填；分配 / 认领 / 转派可选。
   */
  reason?: string | null;
  operatedBy?: (number | null) | User;
  /**
   * 记录自身版本（append-only，恒为 1）。
   */
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 线索跟进流水：记录创建后不可修改或删除，纠错通过追加修正记录实现。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follow-ups".
 */
export interface FollowUp {
  id: number;
  lead: number | Lead;
  broker: number | Broker;
  method: 'phone' | 'wechat' | 'visit' | 'other';
  result: 'connected' | 'no_answer' | 'recommended' | 'appointment' | 'invalid';
  content: string;
  /**
   * "已推荐"结果必须关联统一有效供给中的至少一套房源。
   */
  relatedListings?: (number | Listing)[] | null;
  nextFollowUpAt?: string | null;
  /**
   * 24 小时内纠错时指向被纠正的原跟进记录（追加式，原记录不改）。
   */
  correctionOf?: (number | null) | FollowUp;
  /**
   * 记录自身版本（append-only，恒为 1）。
   */
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  hero?: {
    eyebrow?: string | null;
    heading?: string | null;
    summary?: string | null;
    image?: (number | null) | Media;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * 用于 /news/[slug] 路由，唯一不可重复。
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  category?: ('market' | 'guide' | 'building' | 'industry') | null;
  publishedAt?: string | null;
  /**
   * 首页资讯区策展权重，越小越靠前；0 表示按发布时间倒序。
   */
  featuredOrder?: number | null;
  coverImage?: (number | null) | Media;
  /**
   * 列表/SEO 用，建议 60–120 字。
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedBuildings?: (number | Building)[] | null;
  relatedDistricts?: (number | Location)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "display-tags".
 */
export interface DisplayTag {
  id: number;
  /**
   * 稳定引用键，创建后不可更改；字母开头，仅含字母/数字/下划线/连字符
   */
  code: string;
  /**
   * 可改名，历史记录展示由业务对象快照冻结，不受改名影响
   */
  name: string;
  /**
   * 数值越小越靠前
   */
  sortOrder?: number | null;
  visible?: boolean | null;
  status?: ('active' | 'disabled') | null;
  /**
   * 乐观锁版本号,系统维护
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 房源审核事件流：提交/撤回/通过/驳回。记录创建后不可修改或删除。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-reviews".
 */
export interface ListingReview {
  id: number;
  listing: number | Listing;
  decision: 'submit' | 'withdraw' | 'approve' | 'reject';
  /**
   * 由审核动作单一推导，不可外部指定。
   */
  taskStatus?: ('pending' | 'processing' | 'resolved' | 'cancelled') | null;
  /**
   * 驳回、下架必填；其余动作可选。
   */
  reason?: string | null;
  /**
   * 提交时冻结的房源核心字段快照（不可变）。
   */
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 服务端对快照重算的 SHA-256，用于校验一致性。
   */
  snapshotHash?: string | null;
  submittedBy?: (number | null) | User;
  reviewedBy?: (number | null) | User;
  submittedAt?: string | null;
  reviewedAt?: string | null;
  /**
   * 提交时锁定的房源工作版本号。
   */
  listingVersion?: number | null;
  /**
   * 记录自身版本（append-only，恒为 1）。
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 房源举报处理流：分诊 → 领取 → 核实 → 等待资料 → 提交复核 → 关闭。有效举报暂停供给可见性，不改写审核和发布状态。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-reports".
 */
export interface ListingReport {
  id: number;
  /**
   * 举报指向的房源。
   */
  targetListing: number | Listing;
  /**
   * 举报原因码，决定处理优先级和供给影响判定。
   */
  reason: 'false-info' | 'price-anomaly' | 'leased-not-delisted' | 'policy-violation' | 'other';
  /**
   * 举报人补充的具体问题描述（可选）。
   */
  reasonDetail?: string | null;
  /**
   * 最多 5 张截图或图片证据。
   */
  evidence?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 匿名举报可留空。
   */
  reporterName?: string | null;
  /**
   * 匿名举报可留空；非匿名时用于回访。
   */
  reporterPhone?: string | null;
  /**
   * 存储 IP 哈希用于反垃圾，不存原始 IP。
   */
  reporterIpHash?: string | null;
  /**
   * 由状态转换服务推导，不接受外部直接指定。
   */
  status?: ('pending-triage' | 'assigned' | 'verifying' | 'awaiting-info' | 'submitted-review' | 'closed') | null;
  /**
   * 每次状态变更 +1，用于乐观锁和审计。
   */
  statusVersion?: number | null;
  /**
   * 分诊或领取后指派的处理人。
   */
  assignee?: (number | null) | User;
  /**
   * 仅在关闭时填写：举报成立 / 不成立 / 部分成立。
   */
  conclusion?: ('sustained' | 'dismissed' | 'partial') | null;
  /**
   * 关闭举报时必填，记录关闭依据。
   */
  conclusionReason?: string | null;
  /**
   * 有效举报成立时为 true，影响统一有效供给谓词。
   */
  supplyPaused?: boolean | null;
  supplyPausedAt?: string | null;
  supplyResumedAt?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 公开信息纠错记录：只追加，创建后事实不可改、不可删；status 由后台流转。前台不可读取处理状态。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "information-corrections".
 */
export interface InformationCorrection {
  id: number;
  targetType: 'listing' | 'building';
  targetSlug: string;
  category: 'price' | 'area' | 'availability' | 'media' | 'location' | 'building-fact' | 'other';
  description: string;
  status: 'new' | 'triaged' | 'resolved' | 'rejected';
  requestId: string;
  idempotencyKey: string;
  /**
   * 提交 IP 哈希（反垃圾），不存原始 IP
   */
  reporterIpHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 业主/物业/中介从 /publish 提交的房源投放申请。提交事实不可改、不可删；status 由后台流转，可转为房源草稿。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supply-submissions".
 */
export interface SupplySubmission {
  id: number;
  buildingName: string;
  /**
   * 楼号/单元号/房间号。
   */
  address: string;
  areaSqm: number;
  /**
   * 业主愿意悬赏的佣金月数，成交后支付。有悬赏的申请优先处理。
   */
  commissionMonths: 'none' | '0.5' | '1' | '1.5' | '2';
  rentAmount?: number | null;
  rentUnit?: ('rmb-sqm-day' | 'rmb-month' | 'rmb-seat-month' | 'rmb-total') | null;
  contactPhone: string;
  status: 'pending' | 'contacted' | 'converted' | 'rejected' | 'duplicate';
  assignee?: (number | null) | User;
  contactName?: string | null;
  companyName?: string | null;
  submitterRole?: ('owner' | 'property' | 'agency' | 'operator') | null;
  leaseMode?: ('whole-floor' | 'office' | 'seat' | 'sale') | null;
  fitoutStatus?: ('bare' | 'simple' | 'full' | 'furnished') | null;
  availableFrom?: string | null;
  city?: ((number | null) | Location) | string;
  district?: (number | null) | Location;
  description?: string | null;
  reviewNote?: string | null;
  matchedBuilding?: (number | null) | Building;
  convertedListing?: (number | null) | Listing;
  /**
   * 状态流转到终态时自动写入。
   */
  handledAt?: string | null;
  requestId: string;
  /**
   * requestId + 标准化手机号 + 楼盘名 的哈希。唯一约束防并发重复。
   */
  idempotencyKey: string;
  /**
   * 同源 pathname，不含查询参数。
   */
  sourcePath?: string | null;
  sourceUrl?: string | null;
  consentAccepted?: boolean | null;
  consentPolicyVersion?: string | null;
  /**
   * 反垃圾用，不存原始 IP。
   */
  submitterIpHash?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-partner-applications".
 */
export interface CityPartnerApplication {
  id: number;
  city: number | Location;
  applicantName: string;
  contactPhone: string;
  applicantIdentity: 'owner-property' | 'broker-channel' | 'enterprise-service' | 'local-operations' | 'other';
  otherIdentity?: string | null;
  organizationName?: string | null;
  resourceTypes?:
    | ('building-owner' | 'tenant-demand' | 'broker-network' | 'local-team' | 'government-association' | 'other')[]
    | null;
  otherResource?: string | null;
  experienceSummary?: string | null;
  cooperationPlan?: string | null;
  detailsCompletedAt?: string | null;
  detailsFingerprint?: string | null;
  status: 'pending' | 'contacted' | 'evaluating' | 'qualified' | 'not-fit' | 'withdrawn';
  assignee?: (number | null) | User;
  internalNote?: string | null;
  handledAt?: string | null;
  requestId: string;
  idempotencyKey: string;
  sourcePath: string;
  sourceUrl?: string | null;
  consentAccepted: boolean;
  consentPolicyVersion: string;
  submitterIpHash?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 事务 Outbox：业务事件 append-only。消费器按 event_id + aggregate_version 幂等处理，重复投递不生成重复待办/通知/审计。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domain-events".
 */
export interface DomainEvent {
  id: number;
  /**
   * 稳定唯一 ID（nanoid 21 字符）。Outbox 主键，消费器幂等键。
   */
  eventId: string;
  /**
   * 事件类型枚举（如 listing.published / report.sustained）。
   */
  eventType:
    | 'listing.published'
    | 'listing.unpublished'
    | 'listing.review_submitted'
    | 'listing.review_approved'
    | 'listing.review_rejected'
    | 'report.sustained'
    | 'report.dismissed'
    | 'report.supply_paused'
    | 'report.supply_resumed'
    | 'lead.created'
    | 'lead.assigned'
    | 'lead.transferred'
    | 'lead.reclaimed'
    | 'lead.lost'
    | 'followup.completed'
    | 'followup.corrected'
    | 'sla.breached'
    | 'task.completed'
    | 'task.cancelled'
    | 'correction.created'
    | 'supply-submission.created'
    | 'city-partner-application.created';
  /**
   * 聚合根类型（listing / report / lead / followup / sla）。
   */
  aggregateType:
    | 'listing'
    | 'report'
    | 'lead'
    | 'followup'
    | 'sla'
    | 'task'
    | 'correction'
    | 'supply-submission'
    | 'city-partner-application';
  /**
   * 聚合根 ID 字符串形式（兼容 number / uuid）。
   */
  aggregateId: string;
  /**
   * 聚合版本号（乐观锁，每次状态变更 +1）。与 event_id 共同构成幂等键。
   */
  aggregateVersion: number;
  /**
   * 事件 JSON 负载。Outbox 追加语义：写入后不可变。
   */
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 事件发生时间（UTC 存储，Asia/Shanghai 显示）。
   */
  occurredAt: string;
  /**
   * 消费器处理完成时间。null 表示未处理；非 null 表示已幂等处理。
   */
  processedAt?: string | null;
  /**
   * 消费器处理尝试次数。达到上限后标记为死信，不再自动重试。
   */
  attemptCount?: number | null;
  /**
   * 消费器最后处理错误。成功后清空。
   */
  lastError?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 追加式审计日志：记录所有高风险业务动作。只允许查看和追加，禁止修改或删除。查看详情和导出本身也会被审计。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  /**
   * 稳定唯一 ID（aud_ 前缀，nanoid 风格）。
   */
  auditId: string;
  /**
   * 审计动作类型枚举。
   */
  action:
    | 'listing.create'
    | 'listing.update'
    | 'listing.delete'
    | 'listing.review_submit'
    | 'listing.review_approve'
    | 'listing.review_reject'
    | 'listing.publish'
    | 'listing.unpublish'
    | 'building.create'
    | 'building.update'
    | 'building.delete'
    | 'building.freeze'
    | 'building.restore'
    | 'merchant.create'
    | 'merchant.update'
    | 'merchant.freeze'
    | 'merchant.restore'
    | 'report.triage'
    | 'report.sustain'
    | 'report.dismiss'
    | 'report.pause_supply'
    | 'report.resume_supply'
    | 'report.close'
    | 'lead.create'
    | 'lead.update'
    | 'lead.assign'
    | 'lead.claim'
    | 'lead.transfer'
    | 'lead.to_public_pool'
    | 'lead.reclaim'
    | 'lead.lose'
    | 'lead.stage_transition'
    | 'customer.create'
    | 'customer.update'
    | 'followup.create'
    | 'followup.correct'
    | 'user.create'
    | 'user.disable'
    | 'user.enable'
    | 'user.reset_password'
    | 'role.create'
    | 'role.update'
    | 'role.delete'
    | 'role.assign'
    | 'role.revoke'
    | 'data.import'
    | 'data.export'
    | 'audit.view_detail'
    | 'audit.export';
  /**
   * 操作结果：success / failed。
   */
  result: 'success' | 'failed';
  /**
   * 被操作对象所属 Collection（listings / buildings / leads ...）。
   */
  objectCollection: string;
  /**
   * 被操作对象 ID（字符串形式，兼容 number / uuid）。
   */
  objectId: string;
  /**
   * 操作时对象的版本号（乐观锁）。
   */
  objectVersion: number;
  /**
   * 变更前对象快照（update / delete 时有值）。需 audit:before_after 权限可见。
   */
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 变更后对象快照（create / update 时有值）。需 audit:before_after 权限可见。
   */
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 本次变更的字段路径列表（如 ["stage", "assigneeId"]）。
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 操作人账号 ID。系统动作时为 null。
   */
  subjectUserId?: string | null;
  /**
   * 操作时的角色编码列表（写入时锁定，不随后续权限变更漂移）。
   */
  subjectRoleCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 操作时的所属团队 ID（如有）。
   */
  subjectTeamId?: string | null;
  /**
   * 操作时的城市范围快照（"all" 或城市 ID 数组）。
   */
  subjectCityScope?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 请求追踪 ID（x-request-id），用于跨日志关联同一请求内的多次操作。
   */
  requestId?: string | null;
  /**
   * 客户端 IP（x-forwarded-for 第一跳）。
   */
  ip?: string | null;
  /**
   * 客户端 User-Agent。
   */
  userAgent?: string | null;
  /**
   * HTTP 请求方法（GET / POST / PUT / DELETE）。
   */
  method?: string | null;
  /**
   * 请求 URL 路径（不含 query）。
   */
  path?: string | null;
  /**
   * 操作失败时的错误码（result=failed 时有值）。
   */
  errorCode?: string | null;
  /**
   * 操作失败时的错误信息（result=failed 时有值）。
   */
  errorMessage?: string | null;
  /**
   * 关联的领域事件 ID（如已写入 Outbox）。
   */
  eventId?: string | null;
  /**
   * 操作发生时间（UTC 存储，Asia/Shanghai 显示）。
   */
  occurredAt: string;
  /**
   * 审计日志版本（append-only，恒为 1）。
   */
  version?: number | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 工作流待办：审核 / 举报 / 线索 / 跟进 / 房源维护。状态机 pending → in_progress → completed；pending/in_progress → cancelled。由来源业务事件驱动创建与闭环。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  /**
   * 6 种任务类型：审核 / 举报分诊 / 未分配线索 / 首次跟进 / 下次跟进 / 房源维护。
   */
  taskType:
    | 'review-pending'
    | 'report-triage'
    | 'lead-unassigned'
    | 'followup-first'
    | 'followup-next'
    | 'listing-stale-maintenance';
  /**
   * 来源业务对象 ID（如审核记录 ID / 举报 ID / 线索 ID / 跟进 ID / 房源 ID）。
   */
  sourceId: string;
  /**
   * 来源版本号（与 taskType / sourceId 共同构成幂等键）。
   */
  sourceVersion: number;
  /**
   * 来源业务对象类型，由 taskType 派生（protect hook 自动填充）。
   */
  sourceType: 'listing-review' | 'listing-report' | 'lead' | 'followup' | 'listing';
  /**
   * 任务负责人（领取 / 转派后指派）。
   */
  assignee?: (number | null) | User;
  /**
   * 任务所属团队（用于团队数据范围收窄）。
   */
  team?: (number | null) | Team;
  /**
   * urgent > high > normal > low，决定排序和处理紧急度。
   */
  priority: 'urgent' | 'high' | 'normal' | 'low';
  /**
   * 由 task-service 推导，不接受外部直接指定。
   */
  status?: ('pending' | 'in_progress' | 'completed' | 'cancelled') | null;
  /**
   * 截止时间（UTC 存储，Asia/Shanghai 显示）。逾期是计算属性，不新增持久化状态。
   */
  dueAt: string;
  /**
   * 任务完成时间（completed 状态时填写）。
   */
  completedAt?: string | null;
  /**
   * 任务取消时间（cancelled 状态时填写）。
   */
  cancelledAt?: string | null;
  /**
   * 取消任务时必填，记录来源取消事件或人工取消原因。
   */
  cancellationReason?: string | null;
  /**
   * 完成时关联的来源 domain event ID（Outbox event_id），用于审计回溯。
   */
  completionEventId?: string | null;
  /**
   * buildTask 产出的扩展字段（如 listingId / leadId / eventId），用于审计与下钻。
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 站内通知：审核驳回 / 线索分配转派 / SLA 超时 / 待办变更。由领域事件消费器幂等生成，与业务状态解耦。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * 通知收件人（仅本人可读取 / 标记已读）。
   */
  recipient: number | User;
  /**
   * 通知类型枚举，由触发事件派生。
   */
  type:
    | 'review-rejected'
    | 'lead-assigned'
    | 'lead-transferred'
    | 'sla-breached'
    | 'task-completed'
    | 'task-cancelled'
    | 'supply-submission-created'
    | 'city-partner-application-created';
  /**
   * 通知标题（简洁中文文案）。
   */
  title: string;
  /**
   * 通知正文（含业务上下文摘要）。
   */
  body?: string | null;
  /**
   * 来源业务对象类型（listing-review / lead / followup / task）。
   */
  sourceType: 'listing-review' | 'lead' | 'followup' | 'task' | 'supply-submission' | 'city-partner-application';
  /**
   * 来源业务对象 ID，用于点击通知跳转到详情页。
   */
  sourceId: string;
  /**
   * 触发通知的 Outbox event_id。与 recipient + type 共同构成幂等键。
   */
  eventId: string;
  /**
   * 通知是否已读。已读后不允许回退为未读。
   */
  read?: boolean | null;
  /**
   * 通知已读时间（UTC 存储，Asia/Shanghai 显示）。
   */
  readAt?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'listings';
        value: number | Listing;
      }
    | {
        relationTo: 'buildings';
        value: number | Building;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  processingStatus: 'new' | 'processing' | 'processed';
  processedAt?: string | null;
  processedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'notify-supply-submission-created'
          | 'notify-city-partner-application-created'
          | 'reconcile-city-partner-notification-outbox'
          | 'createCollectionExport'
          | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'notify-supply-submission-created'
        | 'notify-city-partner-application-created'
        | 'reconcile-city-partner-notification-outbox'
        | 'createCollectionExport'
        | 'createCollectionImport'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'business-area-extensions';
        value: number | BusinessAreaExtension;
      } | null)
    | ({
        relationTo: 'city-site-profiles';
        value: number | CitySiteProfile;
      } | null)
    | ({
        relationTo: 'merchants';
        value: number | Merchant;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'brokers';
        value: number | Broker;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'buildings';
        value: number | Building;
      } | null)
    | ({
        relationTo: 'building-merchant-relations';
        value: number | BuildingMerchantRelation;
      } | null)
    | ({
        relationTo: 'listing-merchant-relations';
        value: number | ListingMerchantRelation;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'lead-ownership-history';
        value: number | LeadOwnershipHistory;
      } | null)
    | ({
        relationTo: 'follow-ups';
        value: number | FollowUp;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'display-tags';
        value: number | DisplayTag;
      } | null)
    | ({
        relationTo: 'listing-reviews';
        value: number | ListingReview;
      } | null)
    | ({
        relationTo: 'listing-reports';
        value: number | ListingReport;
      } | null)
    | ({
        relationTo: 'information-corrections';
        value: number | InformationCorrection;
      } | null)
    | ({
        relationTo: 'supply-submissions';
        value: number | SupplySubmission;
      } | null)
    | ({
        relationTo: 'city-partner-applications';
        value: number | CityPartnerApplication;
      } | null)
    | ({
        relationTo: 'domain-events';
        value: number | DomainEvent;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  loginName?: T;
  phone?: T;
  phoneNormalized?: T;
  status?: T;
  roles?: T;
  cityScope?: T;
  team?: T;
  sessionVersion?: T;
  failedLoginCount?: T;
  lockedUntil?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  isBuiltin?: T;
  status?: T;
  dataScope?: T;
  menuPermissions?: T;
  operationPermissions?: T;
  fieldPermissions?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  blurDataUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  immutableCode?: T;
  slug?: T;
  type?: T;
  parent?: T;
  city?: T;
  status?: T;
  frontendVisible?: T;
  centerLatitude?: T;
  centerLongitude?: T;
  description?: T;
  coverImage?: T;
  sortOrder?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-area-extensions_select".
 */
export interface BusinessAreaExtensionsSelect<T extends boolean = true> {
  businessArea?: T;
  boundary?: T;
  extendedCenterLatitude?: T;
  extendedCenterLongitude?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  metroStations?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-site-profiles_select".
 */
export interface CitySiteProfilesSelect<T extends boolean = true> {
  city?: T;
  serviceStatus?: T;
  switcherVisible?: T;
  sortOrder?: T;
  seoTitle?: T;
  seoDescription?: T;
  heroEyebrow?: T;
  heroHeading?: T;
  heroBody?: T;
  heroMedia?: T;
  introHeading?: T;
  introBody?: T;
  contactHeading?: T;
  contactBody?: T;
  featuredRegions?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchants_select".
 */
export interface MerchantsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  contactName?: T;
  contactPhone?: T;
  serviceCities?: T;
  status?: T;
  qualificationStatus?: T;
  qualificationExpiresAt?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  manager?: T;
  cityScope?: T;
  status?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brokers_select".
 */
export interface BrokersSelect<T extends boolean = true> {
  displayName?: T;
  user?: T;
  team?: T;
  serviceCities?: T;
  serviceBusinessAreas?: T;
  employmentStatus?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buildings_select".
 */
export interface BuildingsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  operationalStatus?: T;
  buildingType?: T;
  grade?: T;
  verificationStatus?: T;
  registrationCapability?: T;
  recommendedOrder?: T;
  version?: T;
  city?: T;
  district?: T;
  businessDistrict?: T;
  address?: T;
  nearestMetro?: T;
  latitude?: T;
  longitude?: T;
  completionDate?: T;
  totalFloors?: T;
  propertyCompany?: T;
  propertyFee?: T;
  parkingSpaces?: T;
  developerAndScale?:
    | T
    | {
        developer?: T;
        grossFloorArea?: T;
        typicalFloorArea?: T;
        standardFloorHeight?: T;
        netCeilingHeight?: T;
        efficiencyRate?: T;
      };
  verticalTransport?:
    | T
    | {
        passengerElevators?: T;
        freightElevators?: T;
        zoningNote?: T;
      };
  buildingServices?:
    | T
    | {
        airConditioning?: T;
        network?: T;
        powerSupply?: T;
        accessControl?: T;
        parkingFee?: T;
        serviceHours?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        certificateNumber?: T;
        validFrom?: T;
        validTo?: T;
        publicVisible?: T;
        id?: T;
      };
  verificationInfo?:
    | T
    | {
        verifiedAt?: T;
        priceVerifiedAt?: T;
      };
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  amenities?: T;
  mediaItems?:
    | T
    | {
        resource?: T;
        kind?: T;
        category?: T;
        alt?: T;
        capturedAt?: T;
        isSchematic?: T;
        id?: T;
      };
  summary?: T;
  description?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "building-merchant-relations_select".
 */
export interface BuildingMerchantRelationsSelect<T extends boolean = true> {
  building?: T;
  merchant?: T;
  effectiveFrom?: T;
  effectiveTo?: T;
  createdReason?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-merchant-relations_select".
 */
export interface ListingMerchantRelationsSelect<T extends boolean = true> {
  listing?: T;
  merchant?: T;
  effectiveFrom?: T;
  effectiveTo?: T;
  createdReason?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  listingType?: T;
  building?: T;
  businessType?: T;
  decorationStatus?: T;
  registrationStatus?: T;
  price?:
    | T
    | {
        amount?: T;
        currency?: T;
        period?: T;
        unit?: T;
      };
  rent?: T;
  rentUnit?: T;
  area?: T;
  seats?: T;
  floor?: T;
  minimumLeaseMonths?: T;
  paymentTerms?: T;
  availableFrom?: T;
  spaceDetails?:
    | T
    | {
        efficiencyRate?: T;
        seatMin?: T;
        seatMax?: T;
        orientation?: T;
        netCeilingHeight?: T;
        isDivisible?: T;
        furnitureStatus?: T;
      };
  costTerms?:
    | T
    | {
        depositMonths?: T;
        propertyFeeInclusion?: T;
        propertyFeeAmount?: T;
        invoiceStatus?: T;
        otherFixedCosts?: T;
      };
  isFeatured?: T;
  reviewStatus?: T;
  publicationStatus?: T;
  supplyVisibilityHold?: T;
  version?: T;
  merchant?: T;
  contactBroker?: T;
  verificationInfo?:
    | T
    | {
        verifiedAt?: T;
        priceVerifiedAt?: T;
      };
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  mediaItems?:
    | T
    | {
        resource?: T;
        kind?: T;
        category?: T;
        alt?: T;
        capturedAt?: T;
        isSchematic?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  description?: T;
  dataSource?:
    | T
    | {
        source?: T;
        externalId?: T;
        sourceUrl?: T;
        syncedAt?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  company?: T;
  status?: T;
  source?: T;
  owner?: T;
  district?: T;
  budget?: T;
  area?: T;
  moveInTime?: T;
  interestedListing?: T;
  customer?: T;
  stage?: T;
  ownershipStatus?: T;
  team?: T;
  city?: T;
  areaMin?: T;
  areaMax?: T;
  budgetMin?: T;
  budgetMax?: T;
  currency?: T;
  billingPeriod?: T;
  seatCount?: T;
  leaseMonths?: T;
  moveInDate?: T;
  specialRequirements?: T;
  effectiveCreatedAt?: T;
  effectiveSourceChannel?: T;
  sourceChannel?: T;
  firstValidFollowUpAt?: T;
  lastValidFollowUpAt?: T;
  nextFollowUpAt?: T;
  runtimePolicyVersion?: T;
  firstFollowUpSlaSeconds?: T;
  publicPoolRecycleSeconds?: T;
  claimProtectionSeconds?: T;
  dailyClaimLimit?: T;
  activeLeadCap?: T;
  version?: T;
  notes?: T;
  idempotencyKey?: T;
  sourcePageType?: T;
  sourcePath?: T;
  sourceUrl?: T;
  targetType?: T;
  targetListingSlug?: T;
  targetBuildingSlug?: T;
  sourceSection?: T;
  activeSupplyGroup?: T;
  currentFilters?: T;
  priceSnapshot?: T;
  priceSnapshotSubmittedAt?: T;
  consentAccepted?: T;
  consentPolicyVersion?: T;
  campaign?: T;
  requestId?: T;
  viewingPreference?:
    | T
    | {
        startsAt?: T;
        endsAt?: T;
        timezone?: T;
        status?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  phoneNormalized?: T;
  phoneMaskedSnapshot?: T;
  status?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-ownership-history_select".
 */
export interface LeadOwnershipHistorySelect<T extends boolean = true> {
  lead?: T;
  action?: T;
  ownershipStatus?: T;
  fromOwner?: T;
  toOwner?: T;
  reason?: T;
  operatedBy?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follow-ups_select".
 */
export interface FollowUpsSelect<T extends boolean = true> {
  lead?: T;
  broker?: T;
  method?: T;
  result?: T;
  content?: T;
  relatedListings?: T;
  nextFollowUpAt?: T;
  correctionOf?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        summary?: T;
        image?: T;
      };
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  category?: T;
  publishedAt?: T;
  featuredOrder?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  relatedBuildings?: T;
  relatedDistricts?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "display-tags_select".
 */
export interface DisplayTagsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  visible?: T;
  status?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-reviews_select".
 */
export interface ListingReviewsSelect<T extends boolean = true> {
  listing?: T;
  decision?: T;
  taskStatus?: T;
  reason?: T;
  snapshot?: T;
  snapshotHash?: T;
  submittedBy?: T;
  reviewedBy?: T;
  submittedAt?: T;
  reviewedAt?: T;
  listingVersion?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-reports_select".
 */
export interface ListingReportsSelect<T extends boolean = true> {
  targetListing?: T;
  reason?: T;
  reasonDetail?: T;
  evidence?:
    | T
    | {
        image?: T;
        id?: T;
      };
  reporterName?: T;
  reporterPhone?: T;
  reporterIpHash?: T;
  status?: T;
  statusVersion?: T;
  assignee?: T;
  conclusion?: T;
  conclusionReason?: T;
  supplyPaused?: T;
  supplyPausedAt?: T;
  supplyResumedAt?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "information-corrections_select".
 */
export interface InformationCorrectionsSelect<T extends boolean = true> {
  targetType?: T;
  targetSlug?: T;
  category?: T;
  description?: T;
  status?: T;
  requestId?: T;
  idempotencyKey?: T;
  reporterIpHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supply-submissions_select".
 */
export interface SupplySubmissionsSelect<T extends boolean = true> {
  buildingName?: T;
  address?: T;
  areaSqm?: T;
  commissionMonths?: T;
  rentAmount?: T;
  rentUnit?: T;
  contactPhone?: T;
  status?: T;
  assignee?: T;
  contactName?: T;
  companyName?: T;
  submitterRole?: T;
  leaseMode?: T;
  fitoutStatus?: T;
  availableFrom?: T;
  city?: T;
  district?: T;
  description?: T;
  reviewNote?: T;
  matchedBuilding?: T;
  convertedListing?: T;
  handledAt?: T;
  requestId?: T;
  idempotencyKey?: T;
  sourcePath?: T;
  sourceUrl?: T;
  consentAccepted?: T;
  consentPolicyVersion?: T;
  submitterIpHash?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-partner-applications_select".
 */
export interface CityPartnerApplicationsSelect<T extends boolean = true> {
  city?: T;
  applicantName?: T;
  contactPhone?: T;
  applicantIdentity?: T;
  otherIdentity?: T;
  organizationName?: T;
  resourceTypes?: T;
  otherResource?: T;
  experienceSummary?: T;
  cooperationPlan?: T;
  detailsCompletedAt?: T;
  detailsFingerprint?: T;
  status?: T;
  assignee?: T;
  internalNote?: T;
  handledAt?: T;
  requestId?: T;
  idempotencyKey?: T;
  sourcePath?: T;
  sourceUrl?: T;
  consentAccepted?: T;
  consentPolicyVersion?: T;
  submitterIpHash?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domain-events_select".
 */
export interface DomainEventsSelect<T extends boolean = true> {
  eventId?: T;
  eventType?: T;
  aggregateType?: T;
  aggregateId?: T;
  aggregateVersion?: T;
  payload?: T;
  occurredAt?: T;
  processedAt?: T;
  attemptCount?: T;
  lastError?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  auditId?: T;
  action?: T;
  result?: T;
  objectCollection?: T;
  objectId?: T;
  objectVersion?: T;
  before?: T;
  after?: T;
  changedFields?: T;
  subjectUserId?: T;
  subjectRoleCodes?: T;
  subjectTeamId?: T;
  subjectCityScope?: T;
  requestId?: T;
  ip?: T;
  userAgent?: T;
  method?: T;
  path?: T;
  errorCode?: T;
  errorMessage?: T;
  eventId?: T;
  occurredAt?: T;
  version?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  taskType?: T;
  sourceId?: T;
  sourceVersion?: T;
  sourceType?: T;
  assignee?: T;
  team?: T;
  priority?: T;
  status?: T;
  dueAt?: T;
  completedAt?: T;
  cancelledAt?: T;
  cancellationReason?: T;
  completionEventId?: T;
  metadata?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  body?: T;
  sourceType?: T;
  sourceId?: T;
  eventId?: T;
  read?: T;
  readAt?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  processingStatus?: T;
  processedAt?: T;
  processedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 平台级服务时间（Asia/Shanghai）。用于前台展示"当前服务中/非服务时段"，不含个人顾问排班或联系方式。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisor-service-hours".
 */
export interface AdvisorServiceHour {
  id: number;
  /**
   * 时区固定 Asia/Shanghai
   */
  timezone?: string | null;
  /**
   * 每行一个时段；同一天可多行。start 含、end 不含（HH:MM）。
   */
  weeklyHours?:
    | {
        day: '0' | '1' | '2' | '3' | '4' | '5' | '6';
        start: string;
        end: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 例外日期（YYYY-MM-DD）。不填时段=全天休息；填写则覆盖当天常规时段。
   */
  holidays?:
    | {
        date: string;
        ranges?:
          | {
              start: string;
              end: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  openMessage: string;
  closedMessage: string;
  createdBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  lastModifiedBy?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisor-service-hours_select".
 */
export interface AdvisorServiceHoursSelect<T extends boolean = true> {
  timezone?: T;
  weeklyHours?:
    | T
    | {
        day?: T;
        start?: T;
        end?: T;
        id?: T;
      };
  holidays?:
    | T
    | {
        date?: T;
        ranges?:
          | T
          | {
              start?: T;
              end?: T;
              id?: T;
            };
        id?: T;
      };
  openMessage?: T;
  closedMessage?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "core-stats_widget".
 */
export interface CoreStatsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNotify-supply-submission-created".
 */
export interface TaskNotifySupplySubmissionCreated {
  input: {
    eventId: string;
  };
  output: {
    delivered: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNotify-city-partner-application-created".
 */
export interface TaskNotifyCityPartnerApplicationCreated {
  input: {
    eventId: string;
  };
  output: {
    delivered: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskReconcile-city-partner-notification-outbox".
 */
export interface TaskReconcileCityPartnerNotificationOutbox {
  input?: unknown;
  output: {
    scanned: number;
    queued: number;
    failures: number;
    quarantined: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'roles'
      | 'media'
      | 'locations'
      | 'business-area-extensions'
      | 'city-site-profiles'
      | 'merchants'
      | 'teams'
      | 'brokers'
      | 'amenities'
      | 'buildings'
      | 'building-merchant-relations'
      | 'listing-merchant-relations'
      | 'listings'
      | 'leads'
      | 'customers'
      | 'lead-ownership-history'
      | 'follow-ups'
      | 'pages'
      | 'articles'
      | 'display-tags'
      | 'listing-reviews'
      | 'listing-reports'
      | 'information-corrections'
      | 'supply-submissions'
      | 'city-partner-applications'
      | 'domain-events'
      | 'audit-logs'
      | 'tasks'
      | 'notifications'
      | 'search'
      | 'forms'
      | 'form-submissions'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}