import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * Generated by Payload 3.86, then minimally corrected because the generator's
 * snapshot predated the already-applied 022000 enum-only migration. The
 * duplicate 022000 additions/removals were removed; generated job-stats/meta
 * changes remain, plus the required active-event uniqueness index.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    ALTER TYPE "public"."enum_payload_jobs_log_task_slug"
      ADD VALUE 'reconcile-city-partner-notification-outbox' BEFORE 'createCollectionExport';
    ALTER TYPE "public"."enum_payload_jobs_task_slug"
      ADD VALUE 'reconcile-city-partner-notification-outbox' BEFORE 'createCollectionExport';

    CREATE TABLE "payload_jobs_stats" (
      "id" serial PRIMARY KEY NOT NULL,
      "stats" jsonb,
      "updated_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone
    );

    ALTER TABLE "payload_jobs" ADD COLUMN "meta" jsonb;

    CREATE UNIQUE INDEX "payload_jobs_city_partner_notify_event_active_uq"
      ON "payload_jobs" ("task_slug", (input ->> 'eventId'))
      WHERE "task_slug" = 'notify-city-partner-application-created'
        AND completed_at IS NULL
        AND has_error IS NOT TRUE;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    DROP INDEX "payload_jobs_city_partner_notify_event_active_uq";
    DROP TABLE "payload_jobs_stats" CASCADE;
    ALTER TABLE "payload_jobs" DROP COLUMN "meta";

    ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE text;
    DROP TYPE "public"."enum_payload_jobs_log_task_slug";
    CREATE TYPE "public"."enum_payload_jobs_log_task_slug" AS ENUM(
      'inline',
      'notify-supply-submission-created',
      'notify-city-partner-application-created',
      'createCollectionExport',
      'createCollectionImport'
    );
    ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug"
      SET DATA TYPE "public"."enum_payload_jobs_log_task_slug"
      USING "task_slug"::"public"."enum_payload_jobs_log_task_slug";

    ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE text;
    DROP TYPE "public"."enum_payload_jobs_task_slug";
    CREATE TYPE "public"."enum_payload_jobs_task_slug" AS ENUM(
      'inline',
      'notify-supply-submission-created',
      'notify-city-partner-application-created',
      'createCollectionExport',
      'createCollectionImport'
    );
    ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug"
      SET DATA TYPE "public"."enum_payload_jobs_task_slug"
      USING "task_slug"::"public"."enum_payload_jobs_task_slug";
  `)
}
